-- reset.sql
-- WARNING: This will delete all data!
-- IGNORE THIS FILE IF YOU DON'T WANT TO DELETE ALL DATA!

DROP DATABASE IF EXISTS aaonews;
CREATE DATABASE aaonews;


-- Yo File Yedi SQL RESET GARNU PAREY MATRAI EXECUTE GARNEY