-- reset.sql
-- WARNING: This will delete all data!
-- IGNORE THIS FILE IF YOU DON'T WANT TO DELETE ALL DATA!

DROP DATABASE IF EXISTS aaonews;
CREATE DATABASE aaonews CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;


-- Yo File Yedi SQL RESET GARNU PAREY MATRAI EXECUTE GARNEY